version: 2 

models:
  - name: dim_aircraft
    description: "Aircraft dimension model"
    columns:
      - name: aircraft_code
        description: "the plane type code"
        data_tests:
          - not_null
          
  - name: dim_airport
    description: "Airport dimension model"
    columns:
      - name: airport_code
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: dim_date
    description: "Date dimension model"
    columns:
      - name: date_day
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

sources: 
  - name: stg
    database: postgres
    schema: stg
    tables: 
      - name: aircrafts_data
        identifier: aircrafts_data 
      - name: seats
        identifier: seats 
      - name: airports_data
        identifier: airports_data