models:
  - name: fact_flights
    description: "Fact table for flights"
    columns:
      - name: flight_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
