models:
  - name: fact_flights
    description: "Fact table for flights"
    columns:
      - name: flight_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: fact_tickets
    description: "Fact table for tickets"
    columns:
      - name: ticket_no
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: fact_boarding_passes
    description: "Fact table for boarding passes"
    columns:
      - name: ticket_no , boarding_no, seat_no
        description: "togther they form the primary key for this table"
        data_tests:
          - unique
          - not_null


sources: 
  - name: stg
    database: postgres
    schema: stg
    tables: 
      - name: flights
        identifier: flights 
      - name: boarding_passes
        identifier: boarding_passes
      - name: ticket_flights
        identifier: ticket_flights
      - name: bookings
        identifier: bookings
      - name: tickets
        identifier: tickets